version: 2.3.7
type: ProblemSet
title: my title
description: my description
language: de
license: MIT
authors:
- name: NAME
  email: EMAIL@tugraz.at
  affiliation: TU Graz
- name: name
  email: email
  affiliation: affiliation
- name: name
  email: email
  affiliation: affiliation
- name: name
  email: email
  affiliation: affiliation
maintainers:
- name: NAME
  email: EMAIL@tugraz.at
  affiliation: TU Graz
- name: name
  email: email
  affiliation: affiliation
- name: name
  email: email
  affiliation: affiliation
- name: name
  email: email
  affiliation: affiliation
links:
- description: python
  url: https://www.python.org/
- description: ddd 1
  url: url 1
- description: ddd 2
  url: url 2
supportingMaterial:
- description: python
  url: https://www.python.org/
- description: support
  url: support url
- description: support
  url: support url
keywords:
- python
- python
- testing
- intermediate
- programming
properties:
  studentSubmissionFiles:
  - .\unit1.py
  - .\types.py
  - .\graphics.py
  additionalFiles:
  - .\data
  - .\graphics.dat
  testFiles:
  - .\testfiles
  studentTemplates:
  - .\templates
